UI/WebStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebStore.DomainEntities.DTO.Order;
using WebStore.DomainEntities.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _CartService;
        private readonly IOrderService _OrderService;

        public CartController(ICartService CartService, IOrderService OrderService)
        {
            _CartService = CartService;
            _OrderService = OrderService;
        }

        public IActionResult Details()
        {
            return View();
            //return View(new DetailsViewModel
            //{
            //    CartViewModel = _CartService.TransformCart(),
            //    OrderViewModel = new OrderViewModel()
            //});
        }

        public IActionResult DecrementFromCart(int id)
        {
            _CartService.DecrementFromCart(id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveFromCart(int Id)
        {
            _CartService.RemoveFromCart(Id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveAll()
        {
            _CartService.RemoveAll();
            return RedirectToAction("Details");
        }

        public IActionResult AddToCart(int Id, string ReturnUrl)
        {
            _CartService.AddToCart(Id);
            return Redirect(ReturnUrl);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CheckOut(OrderViewModel model, [FromServices] ILogger<CartController> logger)
        {
            if (!ModelState.IsValid)
                return View("Details", new DetailsViewModel
                {
                    CartViewModel = _CartService.TransformCart(),
                    OrderViewModel = model
                });

            logger.LogInformation("Оформление заказа...");

            var create_order_model = new CreateOrderModel
            {
                OrderViewModel = model,
                //Items = new List<OrderItemDTO>()
                Items = _CartService.TransformCart().Items.Select(item => new OrderItemDTO
                {
                    Id = item.Key.Id,
                    Price = item.Key.Price,
                    Quantity = item.Value
                }).ToList()
            };
            //var order = _OrderService.CreateOrder(model, _CartService.TransformCart(), User.Identity.Name);
            var order = _OrderService.CreateOrder(create_order_model, User.Identity.Name);
            _CartService.RemoveAll();
            return RedirectToAction("OrderConfirmed", new { id = order.Id });
        }

        public IActionResult OrderConfirmed(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.DomainEntities.Entities;
using WebStore.DomainEntities.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _ProductData;

        public CatalogController(IProductData ProductData) => _ProductData = ProductData;

        public IActionResult Shop(int? SectionId, int? BrandId)
        {
            var products = _ProductData.GetProducts(new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId
            });

            var model = new CatalogViewModel
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Products = products.Select(p => new ProductViewModel
                {
                    Id = p.Id,
                    Name = p.Name,
                    ImageUrl = p.ImageUrl,
                    Order = p.Order,
                    Price = p.Price,
                    Brand = p.Brand?.Name ?? string.Empty
                }).OrderBy(p => p.Order).ToArray()
            };

            return View(model);
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null)
                return NotFound();
            return View(new ProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                ImageUrl = product.ImageUrl,
                Order = product.Order,
                Price = product.Price,
                Brand = product.Brand?.Name ?? string.Empty
            });
        }
    }
}

UI/WebStore/Views/Catalog/Partial/_Advertisement.cshtml
<section id="advertisement">
    <div class="container">
        <img src="~/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

UI/WebStore/Views/Catalog/Partial/_Featuresitems.cshtml
@model IEnumerable<ProductViewModel>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Features Items</h2>

    @foreach (var product in Model)
    {
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id">
                        <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                        <h2>@product.Price.ToString("C")</h2>
                        <p>@product.Name</p>
                    </a>
                    <a asp-controller="Cart"
                       asp-action="AddToCart"
                       asp-route-Id="@product.Id"
                       asp-route-ReturnUrl="@Context.Request.Path"
                       class="btn btn-default add-to-cart">
                        <i class="fa fa-shopping-cart"></i>Добавить в корзину
                    </a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id">
                            <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                            <h2>@product.Price.ToString("C")</h2>
                            <p>@product.Name</p>
                        </a>
                        <a asp-controller="Cart"
                           asp-action="AddToCart"
                           asp-route-Id="@product.Id"
                           asp-route-ReturnUrl="@Context.Request.Path"
                           class="btn btn-default add-to-cart">
                            <i class="fa fa-shopping-cart"></i>Добавить в корзину
                        </a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href=""><i class="fa fa-plus-square"></i>Добавить в список желаний</a></li>
                    <li><a href=""><i class="fa fa-plus-square"></i>ДОбавить к сравнению</a></li>
                </ul>
            </div>
        </div>
    </div>
    }

    <ul class="pagination">
        <li class="active"><a href="">1</a></li>
        <li><a href="">2</a></li>
        <li><a href="">3</a></li>
        <li><a href="">&raquo;</a></li>
    </ul>
</div><!--features_items-->